import json
from pathlib import Path
import re

IMAGE_ROOT = Path('images')
OUTPUT_FILE = Path('portfolio-data.js')

LABEL_OVERRIDES = {
    'e commerse': 'E-commerce',
    'fashion shoot': 'Fashion',
    'jwellery shoot': 'Jewellery',
    'pre-wed-shoots': 'Pre Wed Photography',
    'event photography': 'Events',
}

KEY_OVERRIDES = {
    'e commerse': 'ecommerce',
    'fashion shoot': 'fashion',
    'jwellery shoot': 'jewellery',
    'pre-wed-shoots': 'prewed',
    'event photography': 'events',
}


def format_label(folder_name: str) -> str:
    key = folder_name.lower()
    if key in LABEL_OVERRIDES:
        return LABEL_OVERRIDES[key]
    return ' '.join(word.capitalize() for word in re.split(r'[-_\s]+', folder_name.strip()))


def format_key(folder_name: str) -> str:
    key = folder_name.lower()
    if key in KEY_OVERRIDES:
        return KEY_OVERRIDES[key]
    safe = re.sub(r'[^a-z0-9]+', '_', key).strip('_')
    return safe or 'category'


def collect_images(root: Path):
    categories = {}
    if not root.exists() or not root.is_dir():
        raise FileNotFoundError(f"Image folder not found: {root}")

    for path in sorted(root.rglob('*')):
        if path.is_file():
            rel = path.relative_to(root)
            if len(rel.parts) == 1:
                continue
            top = rel.parts[0]
            if top.startswith('.'):
                continue
            category_key = format_key(top)
            label = format_label(top)
            if category_key not in categories:
                categories[category_key] = {
                    'label': label,
                    'base': f"{root}/{top}/".replace('\\', '/'),
                    'files': [],
                }
            relative_file = Path(*rel.parts[1:]).as_posix()
            categories[category_key]['files'].append(relative_file)

    # Remove empty categories and sort file lists
    for cat in list(categories):
        categories[cat]['files'] = sorted(categories[cat]['files'])
        if not categories[cat]['files']:
            del categories[cat]

    return categories


def save_js(categories, output: Path):
    js = '/* Auto-generated by generate_portfolio_data.py */\n'
    js += 'const portfolioFolders = ' + json.dumps(categories, indent=2) + ';\n'
    output.write_text(js, encoding='utf-8')
    print(f'Written {output} with {len(categories)} categories.')


if __name__ == '__main__':
    categories = collect_images(IMAGE_ROOT)
    save_js(categories, OUTPUT_FILE)
