/* Auto-generated by generate_portfolio_data.py */
const portfolioFolders = {
    "prewed":  {
                   "label":  "Pre Wed Photography",
                   "base":  "images/Pre-Wed-Shoots/",
                   "files":  [
                                 "Pre_Wed_1.jpg",
                                 "Pre_Wed_2.jpg",
                                 "Pre_Wed_3.jpg",
                                 "Pre_Wed_4.jpg",
                                 "Pre_Wed_5.jpg",
                                 "Pre_Wed_6.jpg",
                                 "Pre_Wed_7.jpg"
                             ]
               },
    "events":  {
                   "label":  "Events",
                   "base":  "images/event photography/",
                   "files":  [
                                 "Aisec global run/DSC04840.jpg",
                                 "Aisec global run/DSC04849.jpg",
                                 "Aisec global run/DSC04947.jpg",
                                 "Aisec global run/DSC05065.jpg",
                                 "Aisec global run/DSC05133.jpg",
                                 "Aisec global run/DSC05159.jpg",
                                 "Aisec global run/DSC05177.jpg"
                             ]
               },
    "fashion":  {
                    "label":  "Fashion",
                    "base":  "images/Fashion shoot/",
                    "files":  [
                                  "1.jpg",
                                  "DSC01010.jpg",
                                  "DSC01012.jpg",
                                  "DSC01020.jpg",
                                  "DSC01032.jpg",
                                  "DSC01043.jpg",
                                  "DSC01050.jpg",
                                  "DSC01071.jpg",
                                  "DSC01152.jpg",
                                  "DSC01205.jpg",
                                  "DSC01212-3.jpg",
                                  "DSC01271.jpg",
                                  "DSC01308.jpg",
                                  "DSC01315.jpg",
                                  "DSC01337.jpg",
                                  "DSC01351.jpg",
                                  "DSC01372.jpg",
                                  "DSC01473.jpg",
                                  "DSC01499.jpg",
                                  "DSC01511.jpg",
                                  "DSC01535.jpg",
                                  "DSC01566.jpg",
                                  "DSC01568.jpg",
                                  "DSC01977.jpg",
                                  "DSC02012.jpg",
                                  "DSC02013.jpg",
                                  "DSC02074.jpg",
                                  "DSC02087.jpg",
                                  "DSC02339.jpg",
                                  "i.jpg",
                                  "Untitled-01.png",
                                  "Untitled-1.png",
                                  "Untitled-1-Recovered.png",
                                  "Untitled-2.png",
                                  "Untitled-3.png",
                                  "Untitled-4.png",
                                  "Untitled-5.png",
                                  "zz.jpg"
                              ]
                },
    "travel":  {
                   "label":  "Travel",
                   "base":  "images/Travel/",
                   "files":  [
                                 "DSC00448.jpg",
                                 "DSC00453 (1).jpg",
                                 "DSC08865.jpg",
                                 "DSC08873.jpg",
                                 "DSC08874.jpg",
                                 "DSC08883.jpg",
                                 "DSC08921.jpg",
                                 "DSC08928.jpg",
                                 "DSC08932.jpg",
                                 "DSC09014.jpg",
                                 "DSC09111.jpg",
                                 "DSC09117.jpg",
                                 "DSC09138.jpg",
                                 "DSC09327.jpg",
                                 "DSC09810.jpg",
                                 "DSC09817.jpg"
                             ]
               },
    "ecommerce":  {
                      "label":  "E-commerce",
                      "base":  "images/E commerse/",
                      "files":  [
                                    "DSC02419.jpg",
                                    "DSC02425.jpg",
                                    "DSC02426.jpg",
                                    "DSC02429.jpg",
                                    "DSC02430.jpg",
                                    "DSC02433.jpg",
                                    "DSC02434.jpg",
                                    "DSC02435.jpg",
                                    "DSC02437.jpg",
                                    "DSC02439.jpg",
                                    "DSC02440.jpg",
                                    "DSC02441.jpg",
                                    "DSC02443.jpg",
                                    "DSC02444.jpg",
                                    "DSC02447.jpg",
                                    "DSC02448.jpg",
                                    "DSC02449.jpg",
                                    "DSC02500.jpg",
                                    "DSC02501.jpg",
                                    "DSC02502.jpg",
                                    "DSC02504.jpg",
                                    "DSC02505.jpg",
                                    "DSC02507.jpg",
                                    "DSC02508.jpg",
                                    "DSC02511.jpg",
                                    "DSC02512.jpg",
                                    "DSC02513.jpg",
                                    "DSC02520.jpg",
                                    "DSC02521.jpg",
                                    "DSC02522.jpg",
                                    "DSC02523.jpg",
                                    "DSC02524.jpg",
                                    "DSC02525.jpg",
                                    "DSC02526.jpg"
                                ]
                  },
    "jewellery":  {
                      "label":  "Jewellery",
                      "base":  "images/Jwellery Shoot/",
                      "files":  [
                                    "DSC04352.jpg",
                                    "DSC04392.jpg",
                                    "DSC04406.jpg",
                                    "DSC04434.jpg"
                                ]
                  }
};

